# es headless service
apiVersion: v1
kind: Service
metadata:
  name: es-headless-service
  namespace: rootelement
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: es
  selector:
    app: es

---
# es extern service
apiVersion: v1
kind: Service
metadata:
  name: es-extern-service
  namespace: rootelement
spec:
  type: NodePort
  ports:
    - port: 9200
      name: es-http
      nodePort: 30092
      targetPort: 9200
    - port: 9300
      name: es-tcp
      nodePort: 30093
      targetPort: 9300
  selector:
    app: es

---
# es statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-statefulset
  namespace: rootelement
spec:
  selector:
    matchLabels:
      app: es
  serviceName: "es-headless-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          imagePullPolicy: IfNotPresent
          image: ljtnono/re-es
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-tcp
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: es-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: es-log
              mountPath: /usr/share/elasticsearch/logs

      volumes:
        - name: es-config
          configMap:
            name: re-configmap
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml

  # pvc 模板
  volumeClaimTemplates:
    - metadata:
        name: es-data
        namespace: rootelement
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: nfs
        volumeMode: Filesystem
        selector:
          matchLabels:
            pv: es-data-pv
    - metadata:
        name: es-log
        namespace: rootelement
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        storageClassName: nfs
        volumeMode: Filesystem
        selector:
          matchLabels:
            pv: es-log-pv
