# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rootelement
  name: re-service-sys-server
spec:
  selector:
    matchLabels:
      app: re-service-sys-server
  replicas: 1
  template:
    metadata:
      labels:
        app: re-service-sys-server
    spec:
      containers:
        - name: re-service-sys-server
          image: ljtnono/re-service-sys-server:<VERSION>
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "2048Mi"
          ports:
            - containerPort: 8080
              name: web

---
# api-re-frontend service
apiVersion: v1
kind: Service
metadata:
  name: re-service-sys-server
  namespace: rootelement
spec:
  type: NodePort
  ports:
    - port: 8080
      name: web
      nodePort: 30201
      targetPort: 8080
  selector:
    app: re-service-sys-server
