# mysql 数据目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: rootelement
  labels:
    pv: mysql-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/mysql/data
    server: 192.168.8.132

---
# mysql 日志目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-log-pv
  namespace: rootelement
  labels:
    pv: mysql-log-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/mysql/log
    server: 192.168.8.132

---
# nacos 数据目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-data-pv
  namespace: rootelement
  labels:
    pv: nacos-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/nacos/data
    server: 192.168.8.132

---
# nacos 日志目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-log-pv
  namespace: rootelement
  labels:
    pv: nacos-log-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/nacos/log
    server: 192.168.8.132


---
# redis 数据目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  namespace: rootelement
  labels:
    pv: redis-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/redis/data
    server: 192.168.8.132

---
# es 数据目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv
  namespace: rootelement
  labels:
    pv: es-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/es/data
    server: 192.168.8.132

---
# es 日志目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-log-pv
  namespace: rootelement
  labels:
    pv: es-log-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/es/log
    server: 192.168.8.132

---

# minio 数据目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-pv
  namespace: rootelement
  labels:
    pv: minio-data-pv
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/minio/data
    server: 192.168.8.132

---

# minio 配置目录pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-config-pv
  namespace: rootelement
  labels:
    pv: minio-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/nfs/minio/config
    server: 192.168.8.132