apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin-deployment
  namespace: rootelement
spec:
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
        - name: xxl-job-admin
          image: ljtnono/xxl-job-admin:2.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: PARAMS
              value: "--spring.datasource.url=jdbc:mysql://mysql-extern-service:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false --spring.datasource.username=root --spring.datasource.password=re#mysql2022"
---
apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin-service
  namespace: rootelement
spec:
  type: NodePort
  ports:
    - port: 8080
      name: web
      nodePort: 31084
      targetPort: 8080
      protocol: tcp
  selector:
    app: xxl-job-admin