# minio headless service
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: common
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio


---
# minio extern service
apiVersion: v1
kind: Service
metadata:
  name: minio-extern
  namespace: common
spec:
  type: NodePort
  ports:
    - port: 9000
      name: minio-tcp
      nodePort: 30090
      targetPort: 9000
    - port: 9001
      name: minio-console
      nodePort: 30091
      targetPort: 9001
  selector:
    app: minio

---
# minio statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: common
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: "minio-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          imagePullPolicy: IfNotPresent
          image: ljtnono/re-minio
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ACCESS_KEY
              value: lingjiatong
            - name: MINIO_SECRET_KEY
              value: re#minio2022
          ports:
            - containerPort: 9000
              name: minio-tcp
            - containerPort: 9001
              name: minio-console
          volumeMounts:
            - mountPath: /data
              name: minio-data
            - mountPath: /root/.minio
              name: minio-config

  # pvc 模板
  volumeClaimTemplates:
    - metadata:
        name: minio-data
        namespace: common
        annotations:
          # 子目录标签
          nfs.io/storage-path: minio/data
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 60Gi
        storageClassName: nfs-sc
    - metadata:
        name: minio-config
        namespace: common
        annotations:
          # 子目录标签
          nfs.io/storage-path: minio/config
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 2Gi
        storageClassName: nfs-sc
