# redis headless service
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: common
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis


---
# redis extern service
apiVersion: v1
kind: Service
metadata:
  name: redis-extern
  namespace: common
spec:
  type: NodePort
  ports:
    - port: 6379
      name: redis
      nodePort: 30079
      targetPort: 6379
  selector:
    app: redis

---
# redis statefulset

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: common
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          imagePullPolicy: IfNotPresent
          image: ljtnono/re-redis
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /etc/redis/redis.conf
              name: redis-conf
              subPath: redis.conf
            - mountPath: /data
              name: redis-data

      volumes:
        - name: redis-conf
          configMap:
            name: common-configmap
            items:
              - key: redis-standalone.conf
                path: redis.conf

  # pvc 模板
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        namespace: common
        annotations:
          # 子目录标签
          nfs.io/storage-path: redis/data
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: nfs-sc
