# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rootelement
  name: re-gateway
spec:
  selector:
    matchLabels:
      app: re-gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: re-gateway
    spec:
      containers:
        - name: re-gateway
          image: ljtnono/re-gateway:<VERSION>
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "2048Mi"
          ports:
            - containerPort: 8080
              name: web

---
# api-re-frontend service
apiVersion: v1
kind: Service
metadata:
  name: re-gateway
  namespace: rootelement
spec:
  type: NodePort
  ports:
    - port: 8080
      name: web
      nodePort: 30152
      targetPort: 8080
  selector:
    app: re-gateway
